=== civictheme/monorepo-drupal/docroot/modules/custom/civictheme_migrate/assets/schema/civictheme_media.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "Media image entity name (default to filename)"
      },
      "file": {
        "type": "string",
        "description": "Banner featured image url"
      },
      "uuid": {
        "type": "string",
        "description": "UUID for image"
      },
      "alt": {
        "type": "string",
        "description": "Alt tag"
      }
    },
    "required": ["name", "file", "uuid", "alt"]
  }
}

=== civictheme/monorepo-drupal/tests/behat/fixtures/civictheme_migrate.media_content_2.json
[
  {
    "uuid": "f352fb5f-5319-4a09-a039-6b7080b31443",
    "name": "D10 launch.png",
    "file": "https://www.civictheme.io/sites/default/files/images/2022-10/D10%20launch.png",
    "alt": "Test alt text for thumbnail"
  },
  {
    "uuid": "7bed7c3c-ebab-44aa-b19e-0e164ab81d10",
    "name": "test4.png",
    "file": "https://www.civictheme.io/sites/default/files/images/2022-05/Adopt%20-%20The%20DIY%20approach.png",
    "alt": "Test alt text for thumbnail"
  },
  {
    "uuid": "427186ad-c561-4441-9951-28399d8a4923",
    "name": "demo_banner-background.png",
    "file": "https://www.civictheme.io/sites/default/files/demo_banner-background.png",
    "alt": "Test background"
  }
]

=== civictheme/monorepo-drupal/tests/behat/fixtures/civictheme_migrate.media_content_1.json
[
  {
    "uuid": "c97a9b08-f3b0-477b-97f7-8b61f9d4a527",
    "name": "test.png",
    "file": "https://www.civictheme.io/sites/default/files/images/2022-05/Your%20preferred%20agency%20-%20Get%20your%20agency%20to%20adopt%20it.png",
    "alt": "Test alt text for thumbnail"
  },
  {
    "uuid": "7fdce6fd-3bcb-4ffa-b349-2a6eb0b049c4",
    "name": "test2.png",
    "file": "https://www.civictheme.io/sites/default/files/images/2022-05/Adapt%20-%20Modify%20and%20create.png",
    "alt": "Test alt text for thumbnail"
  },
  {
    "uuid": "7966cf0a-598d-4da2-8443-837fccd46109",
    "name": "test3.png",
    "file": "https://www.civictheme.io/sites/default/files/images/2022-05/salsa-campaign.png",
    "alt": ""
  }
]

=== civictheme/monorepo-drupal/tests/behat/fixtures/civictheme_migrate.media_civictheme_image_1.json
[
  {
    "uuid": "c97a9b08-f3b0-477b-97f7-8b61f9d4a527",
    "name": "dummy1.jpg",
    "file": "https://defaultdev.civictheme.io/sites/default/files/images/2023-04/dummy1.jpg",
    "alt": "Dummy file 1"
  },
  {
    "uuid": "7fdce6fd-3bcb-4ffa-b349-2a6eb0b049c4",
    "name": "dummy2.jpg",
    "file": "https://defaultdev.civictheme.io/sites/default/files/images/2023-04/dummy2.jpg",
    "alt": "Dummy file 2"
  }
]

=== civictheme/monorepo-drupal/docroot/modules/custom/civictheme_migrate/tests/fixtures/civictheme_migrate.media_civictheme_image_1.json
[
  {
    "uuid": "c97a9b08-f3b0-477b-97f7-8b61f9d4a527",
    "name": "dummy1.jpg",
    "file": "http://nginx:8080/sites/default/files/dummy1.jpg",
    "alt": "Dummy file 1"
  },
  {
    "uuid": "7fdce6fd-3bcb-4ffa-b349-2a6eb0b049c4",
    "name": "dummy2.jpg",
    "file": "http://nginx:8080/sites/default/files/dummy2.jpg",
    "alt": "Dummy file 2"
  }
]

=== civictheme/monorepo-drupal/tests/behat/fixtures/civictheme_migrate.media_1.json
[
    {
        "name": "\"\"",
        "file": "https://www.govcms.gov.au/sites/default/files/styles/natural/public/2019-10/why-govcms-icon.png?itok=s_QSggn-",
        "uuid": "4c87b5c8-ab89-3dd4-8c06-77b7ebfc0b03",
        "alt": "\"\""
    },
    {
        "name": "\"\"",
        "file": "https://www.govcms.gov.au/sites/default/files/styles/natural/public/2019-10/your-govcms-journey-photo.jpg?itok=pajRr_Rv",
        "uuid": "67b62162-8044-346b-8e2b-09d383e0d662",
        "alt": "\"\""
    },
    {
        "name": "\"\"",
        "file": "https://www.govcms.gov.au/sites/default/files/styles/natural/public/2019-10/support-icon.png?itok=Zg6aTwiQ",
        "uuid": "0e64e2c9-9f08-3d70-8f4f-f4f4bc4a6695",
        "alt": "\"\""
    },
    {
        "name": "Woman helping support another woman on a laptop",
        "file": "https://www.govcms.gov.au/sites/default/files/styles/natural/public/2019-10/support-photo-1.jpg?itok=EJWkbvGU",
        "uuid": "69674331-7c50-334b-b2a6-913854b05d40",
        "alt": "Woman helping support another woman on a laptop"
    }
]
