=== civictheme/monorepo-drupal/docroot/modules/custom/civictheme_migrate/assets/migration_schemas/menu_link_content_civictheme_primary.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "uuid": {
        "type": "string",
        "description": "UUID for menu item"
      },
      "text": {
        "type": "string",
        "description": "Menu item title"
      },
      "link": {
        "type": "string",
        "description": "Url"
      },
      "parent": {
        "type": "string",
        "description": "UUID for parent menu item"
      },
      "weight": {
        "type": "integer",
        "description": "Menu item weight"
      }
    },
    "required": [
      "uuid",
      "link",
      "text",
      "parent",
      "weight"
    ]
  }
}

=== civictheme/monorepo-drupal/tests/behat/fixtures/migrate/civictheme_migrate.menu_civictheme_secondary.json
[
  {
    "uuid": "70062d6d-aa8a-4274-808c-98adf30a6445",
    "link": "internal:/",
    "text": "Secondary 1",
    "parent": "",
    "weight": 0
  },
  {
    "uuid": "de9c50e1-b5fd-4522-abc7-68b52ae2b3ec",
    "link": "internal:/individuals",
    "text": "\n          Secondary 2\n  \n  ",
    "parent": "",
    "weight": 0
  }
]

=== civictheme/monorepo-drupal/tests/behat/fixtures/migrate/civictheme_migrate.menu_link_content_civictheme_footer.json
[
  {
    "uuid": "eb5fe9df-d48e-4a07-b643-25d5d32c4010",
    "link": "internal:/",
    "text": "Test footer 1",
    "parent": "",
    "weight": 0
  },
  {
    "uuid": "32fcfa8a-501a-4af2-981f-a82d4d5d3020",
    "link": "internal:/",
    "text": "Test footer 2",
    "parent": "",
    "weight": 0
  }
]

=== civictheme/monorepo-drupal/tests/behat/fixtures/migrate/civictheme_migrate.menu_civictheme_footer.json
[
  {
    "uuid": "eb5fe9df-d48e-4a07-b643-25d5d32c47dc",
    "link": "internal:/",
    "text": "Footer 1",
    "parent": "",
    "weight": 0
  },
  {
    "uuid": "32fcfa8a-501a-4af2-981f-a82d4d5d3958",
    "link": "internal:/",
    "text": "Footer 2",
    "parent": "",
    "weight": 0
  },
  {
    "uuid": "54c46956-72b7-4afd-b365-164244753cb0",
    "link": "internal:/",
    "text": "Footer 21",
    "parent": "32fcfa8a-501a-4af2-981f-a82d4d5d3958",
    "weight": 0
  }
]

=== civictheme/monorepo-drupal/tests/behat/fixtures/migrate/civictheme_migrate.menu_civictheme_primary.json
[
  {
    "uuid": "0c0d7e6c-075c-3417-9c9a-2b9b08b3e9f5",
    "link": "internal:/",
    "text": "\n          Theme 1\n  \n  ",
    "parent": "",
    "weight": 0
  },
  {
    "uuid": "7148ca27-72d6-3654-8e0a-74ac21fb163f",
    "link": "internal:/individuals",
    "text": "\n          For individuals\n  \n  ",
    "parent": "0c0d7e6c-075c-3417-9c9a-2b9b08b3e9f5",
    "weight": 0
  },
  {
    "uuid": "eceb86c0-8131-3c13-954c-f72ab4ede36e",
    "link": "internal:/",
    "text": "\n          Menu item 1\n  \n  ",
    "parent": "7148ca27-72d6-3654-8e0a-74ac21fb163f",
    "weight": 0
  },
  {
    "uuid": "30cccfbf-3811-380c-9c93-2c4a3d0ed92a",
    "link": "internal:/",
    "text": "\n          Menu item 2\n  \n  ",
    "parent": "7148ca27-72d6-3654-8e0a-74ac21fb163f",
    "weight": 1
  },
  {
    "uuid": "39930274-bd18-3813-8b5a-689cefd4aa19",
    "link": "internal:/",
    "text": "\n          Menu item 3\n  \n  ",
    "parent": "7148ca27-72d6-3654-8e0a-74ac21fb163f",
    "weight": 2
  },
  {
    "uuid": "9c496a31-a8f4-348d-a283-3254416b1e7c",
    "link": "internal:/",
    "text": "\n          Menu item 4\n  \n  ",
    "parent": "7148ca27-72d6-3654-8e0a-74ac21fb163f",
    "weight": 3
  },
  {
    "uuid": "72b90df4-fdbe-37c2-8e4c-88ce76e7c2dc",
    "link": "internal:/businesses",
    "text": "\n          For businesses\n  \n  ",
    "parent": "0c0d7e6c-075c-3417-9c9a-2b9b08b3e9f5",
    "weight": 1
  },
  {
    "uuid": "1a2beaf1-7a06-4d3c-99cc-277251cc4476",
    "link": "internal:/",
    "text": "\n          Menu item 1\n  \n  ",
    "parent": "72b90df4-fdbe-37c2-8e4c-88ce76e7c2dc",
    "weight": 0
  },
  {
    "uuid": "0791539b-28a1-42ba-9cf2-339d45276ccf",
    "link": "internal:/",
    "text": "\n          Menu item 2\n  \n  ",
    "parent": "72b90df4-fdbe-37c2-8e4c-88ce76e7c2dc",
    "weight": 1
  },
  {
    "uuid": "cfe01e53-a486-4688-aa0e-edbe88fad1d3",
    "link": "internal:/",
    "text": "\n          Menu item 3\n  \n  ",
    "parent": "72b90df4-fdbe-37c2-8e4c-88ce76e7c2dc",
    "weight": 2
  },
  {
    "uuid": "0f85a882-f332-4668-b814-385bead56a8f",
    "link": "internal:/",
    "text": "\n          Menu item 4\n  \n  ",
    "parent": "72b90df4-fdbe-37c2-8e4c-88ce76e7c2dc",
    "weight": 3
  },
  {
    "uuid": "80f21ae5-1ca8-33aa-b929-2b7ae34f768b",
    "link": "internal:/government",
    "text": "\n          For government\n  \n  ",
    "parent": "0c0d7e6c-075c-3417-9c9a-2b9b08b3e9f5",
    "weight": 2
  },
  {
    "uuid": "1372b0ec-8a34-4973-aa4c-1142cdc4d3c7",
    "link": "internal:/",
    "text": "\n          Menu item 1\n  \n  ",
    "parent": "80f21ae5-1ca8-33aa-b929-2b7ae34f768b",
    "weight": 0
  },
  {
    "uuid": "107e0d83-c894-442c-813b-ea36828a517e",
    "link": "internal:/",
    "text": "\n          Menu item 2\n  \n  ",
    "parent": "80f21ae5-1ca8-33aa-b929-2b7ae34f768b",
    "weight": 1
  },
  {
    "uuid": "fe0b09bd-98f9-4bfe-9f1d-ce67ee68636a",
    "link": "internal:/",
    "text": "\n          Menu item 3\n  \n  ",
    "parent": "80f21ae5-1ca8-33aa-b929-2b7ae34f768b",
    "weight": 2
  },
  {
    "uuid": "5c44e461-6d1e-4d77-9d5c-82ece8c2934f",
    "link": "internal:/",
    "text": "\n          Menu item 4\n  \n  ",
    "parent": "80f21ae5-1ca8-33aa-b929-2b7ae34f768b",
    "weight": 3
  },
  {
    "uuid": "7bc6de27-5e62-3179-82a7-8f82714b1b29",
    "link": "internal:/news-and-events",
    "text": "\n          News & events\n  \n  ",
    "parent": "0c0d7e6c-075c-3417-9c9a-2b9b08b3e9f5",
    "weight": 3
  },
  {
    "uuid": "be3d0e51-c64c-3ce1-8a03-a9a709d2e730",
    "link": "internal:/",
    "text": "\n          Theme 2\n  \n  ",
    "parent": "",
    "weight": 1
  },
  {
    "uuid": "8fddbd84-79ca-4cd9-b1ee-22dbb0b3c593",
    "link": "internal:/individuals",
    "text": "\n          For individuals\n  \n  ",
    "parent": "be3d0e51-c64c-3ce1-8a03-a9a709d2e730",
    "weight": 0
  },
  {
    "uuid": "7c4adf73-576b-3aef-9b7f-84a4869f87d2",
    "link": "internal:/individuals",
    "text": "\n          For businesses\n  \n  ",
    "parent": "be3d0e51-c64c-3ce1-8a03-a9a709d2e730",
    "weight": 1
  },
  {
    "uuid": "52c5a9ee-10f0-4777-9759-9525ce02fae3",
    "link": "internal:/",
    "text": "\n          Menu item 1\n  \n  ",
    "parent": "7c4adf73-576b-3aef-9b7f-84a4869f87d2",
    "weight": 0
  },
  {
    "uuid": "2484920c-74a7-4f43-a7aa-9fd46c540689",
    "link": "internal:/",
    "text": "\n          Menu item 2\n  \n  ",
    "parent": "7c4adf73-576b-3aef-9b7f-84a4869f87d2",
    "weight": 1
  },
  {
    "uuid": "5d660ec8-811c-4c39-9460-281caf2920d6",
    "link": "internal:/",
    "text": "\n          Menu item 3\n  \n  ",
    "parent": "7c4adf73-576b-3aef-9b7f-84a4869f87d2",
    "weight": 2
  },
  {
    "uuid": "98a2c6d3-613b-446a-aaa8-6d7d4b5fb27e",
    "link": "internal:/government",
    "text": "\n          For government\n  \n  ",
    "parent": "be3d0e51-c64c-3ce1-8a03-a9a709d2e730",
    "weight": 2
  },
  {
    "uuid": "e07eca56-2fb2-3af6-a65a-60c4b4a30a3f",
    "link": "internal:/",
    "text": "\n          Menu item 5\n  \n  ",
    "parent": "98a2c6d3-613b-446a-aaa8-6d7d4b5fb27e",
    "weight": 4
  },
  {
    "uuid": "72ade8f6-23df-45fa-911b-8d69cc2eb557",
    "link": "internal:/news-and-events",
    "text": "\n          News & events\n  \n  ",
    "parent": "be3d0e51-c64c-3ce1-8a03-a9a709d2e730",
    "weight": 3
  },
  {
    "uuid": "84e1e9da-6348-3fff-8043-01024660bd2d",
    "link": "internal:/",
    "text": "\n          Theme 3\n  \n  ",
    "parent": "",
    "weight": 2
  },
  {
    "uuid": "f48bb8d8-eb36-487b-9857-b19f935099d1",
    "link": "internal:/individuals",
    "text": "\n          For individuals\n  \n  ",
    "parent": "84e1e9da-6348-3fff-8043-01024660bd2d",
    "weight": 0
  },
  {
    "uuid": "27ad5974-b303-4fb8-9b52-52eae623e123",
    "link": "internal:/businesses",
    "text": "\n          For businesses\n  \n  ",
    "parent": "84e1e9da-6348-3fff-8043-01024660bd2d",
    "weight": 1
  },
  {
    "uuid": "9895b3f1-4e9d-4503-a6cf-89fafb135064",
    "link": "internal:/government",
    "text": "\n          For government\n  \n  ",
    "parent": "84e1e9da-6348-3fff-8043-01024660bd2d",
    "weight": 2
  },
  {
    "uuid": "1b896b12-204f-472b-9e01-c8b8893c8bc4",
    "link": "internal:/news-and-events",
    "text": "\n          News & events\n  \n  ",
    "parent": "84e1e9da-6348-3fff-8043-01024660bd2d",
    "weight": 3
  },
  {
    "uuid": "5fb9140c-7fcb-3374-9930-060936d96128",
    "link": "internal:/",
    "text": "\n          Theme 4\n  \n  ",
    "parent": "",
    "weight": 3
  },
  {
    "uuid": "03a2ed2f-ff9f-4756-9132-a8288033c4eb",
    "link": "internal:/individuals",
    "text": "\n          For individuals\n  \n  ",
    "parent": "5fb9140c-7fcb-3374-9930-060936d96128",
    "weight": 0
  },
  {
    "uuid": "c6a40ac0-4113-4fa5-9a71-c7a73f164d02",
    "link": "internal:/businesses",
    "text": "\n          For businesses\n  \n  ",
    "parent": "5fb9140c-7fcb-3374-9930-060936d96128",
    "weight": 1
  },
  {
    "uuid": "d11806ad-a7cb-4574-b758-726b70001c9c",
    "link": "internal:/government",
    "text": "\n          For government\n  \n  ",
    "parent": "5fb9140c-7fcb-3374-9930-060936d96128",
    "weight": 2
  },
  {
    "uuid": "56762a95-7042-4c26-ae09-1f071eacb363",
    "link": "internal:/news-and-events",
    "text": "\n          News & events\n  \n  ",
    "parent": "5fb9140c-7fcb-3374-9930-060936d96128",
    "weight": 3
  }
]
