=== civictheme/monorepo-drupal/docroot/modules/custom/civictheme_migrate/assets/migration_schemas/node_civictheme_page.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "description": "Unique ID for the node"
      },
      "title": {
        "type": "string",
        "description": "Page title"
      },
      "alias": {
        "type": "string",
        "description": "Page url alias, validation ensures backslash at start of url alias",
        "pattern": "^\\/[\\S]+$"
      },
      "summary": {
        "type": "string",
        "description": "Page summary"
      },
      "topics": {
        "type": "string",
        "description": "Comma delimited page topics"
      },
      "thumbnail": {
        "type": "array",
        "items": {
          "type": "string",
          "description": "Media uuid"
        }
      },
      "vertical_spacing": {
        "type": "string",
        "pattern": "none|top|bottom|both",
        "description": "Page level vertical spacing"
      },
      "show_toc": {
        "type": "boolean",
        "description": "Whether to hide table of contents"
      },
      "hide_sidebar": {
        "type": "boolean",
        "description": "Whether to hide sidebar"
      },
      "show_last_updated_date": {
        "type": "boolean",
        "description": "Determines if last updated date is visible or not"
      },
      "last_updated_date": {
        "type": "string",
        "description": "Last updated date in `D MMM YYYY`format"
      },
      "banner": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "description": "Hardcoded Merlin UI Output",
            "pattern": "container"
          },
          "children": {
            "type": "array",
            "contains": {
              "type": "object",
              "properties": {
                "theme": {
                  "type": "string",
                  "description": "Banner theme",
                  "pattern": "light|dark"
                },
                "title": {
                  "type": "string",
                  "description": "Banner title"
                },
                "banner_type": {
                  "type": "string",
                  "description": "Type of banner",
                  "pattern": "default|large"
                },
                "blend_mode": {
                  "type": "string",
                  "description": "Banner blend mode",
                  "pattern": "color|color-burn|darken|difference|exclusion|hard-light|hue|lighten|luminosity|multiply|normal|overlay|saturation|screen|soft-light"
                },
                "featured_image": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "description": "Media uuid"
                  }
                },
                "background": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "description": "Media uuid"
                  }
                },
                "hide_breadcrumb": {
                  "type": "boolean",
                  "description": "Whether to hide breadcrumb in banner"
                }
              }
            }
          }
        }
      }
    },
    "required": [
      "id",
      "title"
    ]
  }
}

=== civictheme/monorepo-drupal/tests/behat/fixtures/civictheme_migrate.page_content_1.json
[
  {
    "id": "4593761e-8a5d-4564-8c0e-2126fb4f3338",
    "title": "[TEST] Migrated Content 1",
    "alias": "/test/migrated-content-1",
    "summary": "Summary for [TEST] Migrated Content 1",
    "topics": "[TEST] Topic 1,[TEST] Topic 2,[TEST] Topic 3,[TEST] Topic 4",
    "thumbnail": ["f352fb5f-5319-4a09-a039-6b7080b31443"],
    "vertical_spacing": "top",
    "hide_sidebar": true,
    "show_last_updated_date": true,
    "last_updated_date": "8 Oct 2022",
    "show_toc": true,
    "banner": {
      "type": "container",
      "children" : [
        {
          "theme": "dark",
          "title": "[TEST] Banner title - Migrated Content 1",
          "banner_type": "large",
          "blend_mode": "darken",
          "featured_image": [
            "7bed7c3c-ebab-44aa-b19e-0e164ab81d10"
          ],
          "background": [
            "427186ad-c561-4441-9951-28399d8a4923"
          ],
          "hide_breadcrumb": true
        }
      ]
    }
  }
]
